[[redirects]]
  # Redirect if page not found, 404 http error occured.
  from = "/*"
  to = "./index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"